############################
## Author
############################

author:
  name: Friends of Bramley Park
  image: author.png
  greeting: "Friends of Bramley Park is a community group run by volunteers working closely with Leeds Council's Parks department. Our aim is to improve the park, run events and increase enagagement between the park and the local community."
#  icon: ":deciduous_tree:"

############################
## Links
############################

links:
  # - github: https://github.com/Friends-of-Bramley-Park/friendsofbramleypark.com
  # - link: https://github.com/Friends-of-Bramley-Park/friendsofbramleypark.com#readme
  
  - facebook: https://www.facebook.com/groups/3395248527372540
  - whatsapp: https://whatsapp.com/channel/0029VbAtkjP0wak1lIdzMH14
  - email: mailto:friendsofbramleypark@gmail.com
  - newsletter: https://eepurl.com/jm461E
  - paypal: https://www.paypal.com/paypalme/bramleypark
  - Gardening-Club: https://www.facebook.com/events/1290310238992526/1290310295659187
  - Bramley-Market: https://www.facebook.com/profile.php?id=61581356734922
  
  # - signal:
  # - codepen:
  # - dev:
  # - website:
  # - x-twitter:
  # - mastodon:
  # - linkedin:
  # - instagram:
  # - reddit:
  # - telegram:
  # - discord:
  # - orcid:
  # - slack:
  # - stack-overflow:
  # - twitch:
  # - patreon:
  # - soundcloud:
  # - dribbble:
  # - stack-exchange:
  # - tiktok:
  # - youtube:
  # - keybase:
  # - flickr:
  # - tumblr:
  # - kickstarter:
  # - snapchat:
  # - bluesky:
  # - bitbucket:
  # - bandcamp:
  # - etsy:
  # - spotify:
  # - pinterest:
  # - strava:
  # - untappd:
  # - skype:
  # - medium:
  # - foursquare:
  # - apple:
  # - amazon:
  # - google:
  # - windows:


############################
## Colunms of Links
############################

# between 2 & 6 columns are supported (both incl)
columns: 4

###########################
## Icon text
###########################

# add the icon name to each icon
icontext: true

############################
## Tooltips
############################

# add tooltips on all icons
tooltip: false

###############################
## OpenGraph & Twitter Cards
###############################

title: friendsofbramleypark.com
description: "Friends of Bramley Park"
images:
  - thumbnail.png

###############################
## Style
###############################

monochrome: true
